/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OperatorGUI;

/**
 *
 * @author hazem
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        menuLabel = new javax.swing.JLabel();
        PayBillsButtton = new javax.swing.JButton();
        PrintBillsButton = new javax.swing.JButton();
        CancelSubscriptionButton = new javax.swing.JButton();
        EnterReadinButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(102, 102, 102));
        menuLabel.setText(" operator menu");

        PayBillsButtton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PayBillsButtton.setForeground(new java.awt.Color(204, 0, 0));
        PayBillsButtton.setText("Pay Bills");
        PayBillsButtton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PayBillsButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBillsButttonActionPerformed(evt);
            }
        });

        PrintBillsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PrintBillsButton.setForeground(new java.awt.Color(204, 0, 0));
        PrintBillsButton.setText("Print Bills");
        PrintBillsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PrintBillsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBillsButtonActionPerformed(evt);
            }
        });

        CancelSubscriptionButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CancelSubscriptionButton.setForeground(new java.awt.Color(204, 0, 0));
        CancelSubscriptionButton.setText("Cancel Subscription");
        CancelSubscriptionButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelSubscriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelSubscriptionButtonActionPerformed(evt);
            }
        });

        EnterReadinButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EnterReadinButton.setForeground(new java.awt.Color(204, 0, 0));
        EnterReadinButton.setText("Validate Reading");
        EnterReadinButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EnterReadinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterReadinButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EnterReadinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelSubscriptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrintBillsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PayBillsButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PayBillsButtton)
                .addGap(55, 55, 55)
                .addComponent(PrintBillsButton)
                .addGap(51, 51, 51)
                .addComponent(EnterReadinButton)
                .addGap(47, 47, 47)
                .addComponent(CancelSubscriptionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PayBillsButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBillsButttonActionPerformed
 payBills pb=new payBills();
        this.setVisible(false);
        pb.setVisible(true);
 
      
       
    }//GEN-LAST:event_PayBillsButttonActionPerformed

    private void PrintBillsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBillsButtonActionPerformed
PrintBills Pb=new PrintBills();
        this.setVisible(false);
        Pb.setVisible(true);
    }//GEN-LAST:event_PrintBillsButtonActionPerformed

    private void EnterReadinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterReadinButtonActionPerformed
   EnterReading ER=new EnterReading();
        this.setVisible(false);
        ER.setVisible(true);
    }//GEN-LAST:event_EnterReadinButtonActionPerformed

    private void CancelSubscriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelSubscriptionButtonActionPerformed
   CancelSubscription CS=new CancelSubscription();
        this.setVisible(false);
        CS.setVisible(true);
    }//GEN-LAST:event_CancelSubscriptionButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
    Login l=new Login();
        setVisible(false);
        l.setVisible(true);
        
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelSubscriptionButton;
    private javax.swing.JButton EnterReadinButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton PayBillsButtton;
    private javax.swing.JButton PrintBillsButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel menuLabel;
    // End of variables declaration//GEN-END:variables

    private payBills payBills() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
