/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OperatorGUI;

import AdminRole.operator;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hazem
 */
public class PrintBills extends javax.swing.JFrame {

    /**
     * Creates new form PrintBills
     */
    public PrintBills() {
        initComponents();
        GenerateButton.setVisible(false);
        metercodeField1.setEditable(false);
        FnameField.setEditable(false);
        LnameField.setEditable(false);
        costField.setEditable(false);
        ReadingField.setEditable(false);
        LnameField.setEditable(false);
        costField.setEditable(false);
        ReadingField.setEditable(false);
        AddressField.setEditable(false);
        AgeField.setEditable(false);
        RegionField.setEditable(false);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        MeterCodeLabel = new javax.swing.JLabel();
        MeterCodeField = new javax.swing.JTextField();
        GenerateButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        PrintBilljButton = new javax.swing.JButton();
        FnameLabel = new javax.swing.JLabel();
        LnameLabel = new javax.swing.JLabel();
        CostLabel = new javax.swing.JLabel();
        ReadingLabel = new javax.swing.JLabel();
        FnameField = new javax.swing.JTextField();
        LnameField = new javax.swing.JTextField();
        costField = new javax.swing.JTextField();
        ReadingField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        metercodeField1 = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        RegionField = new javax.swing.JTextField();
        LnameLabel1 = new javax.swing.JLabel();
        CostLabel1 = new javax.swing.JLabel();
        ReadingLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        MeterCodeLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MeterCodeLabel.setForeground(new java.awt.Color(204, 0, 0));
        MeterCodeLabel.setText("Enter the Meter Code ");

        MeterCodeField.setBackground(new java.awt.Color(102, 102, 102));
        MeterCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeterCodeFieldActionPerformed(evt);
            }
        });

        GenerateButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        GenerateButton.setText("Generate");
        GenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateButtonActionPerformed(evt);
            }
        });

        ReturnButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ReturnButton.setText("Return");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Print Customer Bill");

        SearchButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        PrintBilljButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PrintBilljButton.setText("Print bill");
        PrintBilljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBilljButtonActionPerformed(evt);
            }
        });

        FnameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FnameLabel.setText("First Name");

        LnameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LnameLabel.setText("Last name");

        CostLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CostLabel.setText("cost");

        ReadingLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ReadingLabel.setText("Reading");

        FnameField.setBackground(new java.awt.Color(102, 102, 102));
        FnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameFieldActionPerformed(evt);
            }
        });

        LnameField.setBackground(new java.awt.Color(102, 102, 102));
        LnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameFieldActionPerformed(evt);
            }
        });

        costField.setBackground(new java.awt.Color(102, 102, 102));
        costField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costFieldActionPerformed(evt);
            }
        });

        ReadingField.setBackground(new java.awt.Color(102, 102, 102));
        ReadingField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadingFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Meter code");

        metercodeField1.setBackground(new java.awt.Color(102, 102, 102));
        metercodeField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metercodeField1ActionPerformed(evt);
            }
        });

        AddressField.setBackground(new java.awt.Color(102, 102, 102));
        AddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFieldActionPerformed(evt);
            }
        });

        AgeField.setBackground(new java.awt.Color(102, 102, 102));
        AgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeFieldActionPerformed(evt);
            }
        });

        RegionField.setBackground(new java.awt.Color(102, 102, 102));
        RegionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegionFieldActionPerformed(evt);
            }
        });

        LnameLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LnameLabel1.setText("Address");

        CostLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CostLabel1.setText("Age");

        ReadingLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ReadingLabel1.setText("Region");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(PrintBilljButton)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(FnameLabel)
                                                    .addGap(153, 153, 153)
                                                    .addComponent(SearchButton)
                                                    .addGap(109, 109, 109))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ReadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(LnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(CostLabel)
                                                                    .addComponent(ReadingLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(CostLabel1)
                                                                    .addComponent(jLabel2))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(LnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(FnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(ReadingField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(RegionField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(metercodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(GenerateButton)
                                            .addComponent(MeterCodeLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MeterCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(226, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(196, 196, 196)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MeterCodeLabel)
                            .addComponent(MeterCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(SearchButton)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(metercodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FnameLabel)
                                    .addComponent(FnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LnameLabel)
                                    .addComponent(LnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(CostLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ReadingLabel)
                                    .addComponent(ReadingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LnameLabel1)
                                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CostLabel1))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RegionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReadingLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PrintBilljButton)
                                    .addComponent(GenerateButton))
                                .addGap(51, 51, 51)
                                .addComponent(ReturnButton)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        operator op=new operator();
    try {
       if(op.Search(MeterCodeField.getText())) 
        {
            JOptionPane.showMessageDialog(this, "CustomerFound!");
               ArrayList<String>v=new ArrayList<>();
             v=op.retriveCustomerdata(MeterCodeField.getText());
        metercodeField1.setText(v.get(0));
        FnameField.setText(v.get(1));
        LnameField.setText(v.get(2));
        costField.setText(v.get(3));
        ReadingField.setText(v.get(4));
        LnameField.setText(v.get(2));
        costField.setText(v.get(3));
        ReadingField.setText(v.get(4));
        AddressField.setText(v.get(5));
        AgeField.setText(v.get(6));
        RegionField.setText(v.get(7));
         GenerateButton.setVisible(true);


        }
        else{
            JOptionPane.showMessageDialog(this, "No Customer Found ! Meter Code is incorrect");
            MeterCodeField.setText("");
    }                                            
    } catch (SQLException ex) {
        Logger.getLogger(payBills.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
         menu m=new menu();
        setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void GenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateButtonActionPerformed
       operator op=new operator();
        ArrayList<String>v=new ArrayList<>();
        area.setText(area.getText()+"************************\n");
        area.setText(area.getText()+"*     Bills Receipt    *\n");
        area.setText(area.getText()+"************************\n");
        Date obj=new Date();
        String date=obj.toString();
        area.setText(area.getText()+"\n"+date+"\n\n");
        area.setText(area.getText()+"\n the meter code Name is : "+metercodeField1.getText()+"\n\n");
        area.setText(area.getText()+"\n First Name is : "+FnameField.getText()+"\n\n");
        area.setText(area.getText()+"\n Last Name is : "+LnameField.getText()+"\n\n");
        area.setText(area.getText()+"\n the cost  is : "+costField.getText()+"\n\n");
        area.setText(area.getText()+"\n the Reading is : "+ReadingField.getText()+"\n\n");
        area.setText(area.getText()+"\n The Address is : "+AddressField.getText()+"\n\n");
        area.setText(area.getText()+"\n Age  is : "+AgeField.getText()+"\n\n");
        area.setText(area.getText()+"\n Region is : "+RegionField.getText()+"\n\n");
        area.setText(area.getText()+"                         Singnature\n");
        FnameField.setText("");
        LnameField.setText("");
        costField.setText("");
        ReadingField.setText("");
        MeterCodeField.setText("");
        metercodeField1.setText("");
        AddressField.setText("");
        AgeField.setText("");
        RegionField.setText("");
        GenerateButton.setVisible(false);
        
        area.setText(area.getText()+"************************\n");
        area.setText(area.getText()+"*     Bills Receipt    *\n");
        area.setText(area.getText()+"************************\n");
        Date obj=new Date();
        String date=obj.toString();
        area.setText(area.getText()+"\n"+date+"\n\n");
        area.setText(area.getText()+"\n the meter code Name is : "+metercodeField1.getText()+"\n\n");
        area.setText(area.getText()+"\n First Name is : "+FnameField.getText()+"\n\n");
        area.setText(area.getText()+"\n Last Name is : "+LnameField.getText()+"\n\n");
        area.setText(area.getText()+"\n the cost  is : "+costField.getText()+"\n\n");
        area.setText(area.getText()+"\n the Reading is : "+ReadingField.getText()+"\n\n");
        area.setText(area.getText()+"\n Last Name is : "+AddressField.getText()+"\n\n");
        area.setText(area.getText()+"\n the cost  is : "+AgeField.getText()+"\n\n");
        area.setText(area.getText()+"\n the Reading is : "+RegionField.getText()+"\n\n");
        area.setText(area.getText()+"                         Singnature\n");
        FnameField.setText("");
        LnameField.setText("");
        costField.setText("");
        ReadingField.setText("");
        MeterCodeField.setText("");
        metercodeField1.setText("");
        AddressField.setText("");
        AgeField.setText("");
        RegionField.setText("");
        GenerateButton.setVisible(false);
    }//GEN-LAST:event_GenerateButtonActionPerformed

    private void MeterCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeterCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MeterCodeFieldActionPerformed

    private void PrintBilljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBilljButtonActionPerformed
        try {
            area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PrintBills.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintBilljButtonActionPerformed

    private void FnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameFieldActionPerformed
        FnameField.setEditable(false);
    }//GEN-LAST:event_FnameFieldActionPerformed

    private void metercodeField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metercodeField1ActionPerformed
     metercodeField1.setEditable(false);
    }//GEN-LAST:event_metercodeField1ActionPerformed

    private void LnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameFieldActionPerformed
     LnameField.setEditable(false);
    }//GEN-LAST:event_LnameFieldActionPerformed

    private void costFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costFieldActionPerformed
     costField.setEditable(false);
    }//GEN-LAST:event_costFieldActionPerformed

    private void ReadingFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadingFieldActionPerformed
     ReadingField.setEditable(false);
    }//GEN-LAST:event_ReadingFieldActionPerformed

    private void AddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFieldActionPerformed
        AddressField.setEditable(false);
    }//GEN-LAST:event_AddressFieldActionPerformed

    private void AgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeFieldActionPerformed
       AgeField.setEditable(false);
    }//GEN-LAST:event_AgeFieldActionPerformed

    private void RegionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegionFieldActionPerformed
        RegionField.setEditable(false);
    }//GEN-LAST:event_RegionFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintBills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel CostLabel;
    private javax.swing.JLabel CostLabel1;
    private javax.swing.JTextField FnameField;
    private javax.swing.JLabel FnameLabel;
    private javax.swing.JButton GenerateButton;
    private javax.swing.JTextField LnameField;
    private javax.swing.JLabel LnameLabel;
    private javax.swing.JLabel LnameLabel1;
    private javax.swing.JTextField MeterCodeField;
    private javax.swing.JLabel MeterCodeLabel;
    private javax.swing.JButton PrintBilljButton;
    private javax.swing.JTextField ReadingField;
    private javax.swing.JLabel ReadingLabel;
    private javax.swing.JLabel ReadingLabel1;
    private javax.swing.JTextField RegionField;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextArea area;
    private javax.swing.JTextField costField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField metercodeField1;
    // End of variables declaration//GEN-END:variables
}